---
# Source: query-test/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: query-test-0
  namespace: default
stringData:
  CLUSTER: "pod-logs-feature-test"
  LOKI_PASS: "lokipassword"
  LOKI_TENANTID: "1"
  LOKI_URL: "http://loki.loki.svc:3100/loki/api/v1/query"
  LOKI_USER: "loki"
---
# Source: query-test/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: query-test-0
  namespace: default
data:
  queries.json: |-
    {
      "queries": 
      [
        {
          "query": "count_over_time({cluster=\"$CLUSTER\", job=\"production/busybox\", namespace=\"production\"}[1h])",
          "type": "logql"
        },
        {
          "query": "count_over_time({cluster=\"$CLUSTER\", job=\"dev-pod\", namespace=\"development\"}[1h])",
          "type": "logql"
        }
      ]
    }
---
# Source: query-test/templates/tests/test-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: query-test-0
  namespace: default
  labels:
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "query-test"
    app.kubernetes.io/version: 0.3.4
    helm.sh/chart: "query-test-0.3.4"
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "0"
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  restartPolicy: Never
  nodeSelector:
        kubernetes.io/os: linux
  containers:
    - name: query-test
      image: "ghcr.io/grafana/helm-chart-toolbox-query-test:0.3.4"
      command:
        - bash
        - -c
        - |
          for i in $(seq 1 10); do
            echo "Running test... ($i/10)"
            if /usr/bin/query-test.sh /etc/test/queries.json; then
              exit 0
            fi
            sleep 30
          done
          exit 1
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
      envFrom:
        - secretRef:
            name: query-test-0
      volumeMounts:
        - name: queries
          mountPath: /etc/test
  volumes:
    - name: queries
      configMap:
        name: query-test-0
