#!/usr/bin/env bash

scriptDir=$(dirname "$(readlink -f "$0")")
source "${scriptDir}/cluster/kind.sh"
source "${scriptDir}/cluster/aks.sh"
source "${scriptDir}/cluster/eks.sh"
source "${scriptDir}/cluster/gke.sh"
source "${scriptDir}/cluster/minikube.sh"
source "${scriptDir}/cluster/openshift.sh"

usage() {
  echo "USAGE: delete-cluster [<test-dir>]"
  echo ""
  echo "Deletes a Kubernetes Cluster used for testing purposes."
  echo ""
  echo "  <test-dir>           - The test directory. Expects this file:"
  echo "    test-plan.yaml        - The test plan."
}

testDir=$(pwd)
testPlan="${testDir}/test-plan.yaml"
clusterName=$(yq eval '.name + "test-cluster"' "${testPlan}")
clusterType=$(yq eval '.cluster.type' "${testPlan}")
if [ -z "${clusterType}" ]; then
  echo "Cluster type not specified in test plan. Please set 'cluster.type' in ${testPlan}."
  usage
  exit 1
fi

set -eo pipefail  # Exit immediately if a command fails.

echo "### Deleting cluster: ${clusterName} of type: ${clusterType}"
if [ "${clusterType}" = "aks" ]; then             deleteAKSCluster "${testPlan}"
elif [ "${clusterType}" = "eks" ]; then           deleteEKSCluster "${testPlan}"
elif [ "${clusterType}" = "gke" ]; then           deleteGKECluster "${testPlan}"
elif [ "${clusterType}" = "gke-autopilot" ]; then deleteGKEAutopilotCluster "${testPlan}"
elif [ "${clusterType}" = "kind" ]; then          deleteKindCluster "${testPlan}"
elif [ "${clusterType}" = "minikube" ]; then      deleteMinikubeCluster "${testPlan}"
elif [ "${clusterType}" = "openshift" ]; then     deleteOpenShiftCluster "${testPlan}"
fi
