#!/usr/bin/env bash

usage() {
  echo "USAGE: run-tests [<test-dir>]"
  echo ""
  echo "Runs any installed toolbox tests"
  echo ""
  echo "  <test-dir>           - The test directory. Expects this file:"
  echo "    test-plan.yaml        - The test plan."
}

set -eo pipefail  # Exit immediately if a command fails.

testDir=$(pwd)
testPlan="${testDir}/test-plan.yaml"

echo; echo "### Running tests"
testCount=$(yq eval '.tests | length - 1' "${testPlan}")
if [ "${testCount}" -ge 0 ]; then
  for i in $(seq 0 "${testCount}"); do
    testType=$(yq eval ".tests[${i}].type" "${testPlan}")
    echo "#### Running test: ${testType}"
    if [ "${testType}" == "query-test" ]; then
      helm test query-test --namespace toolbox --hide-notes --logs
    fi
  done
fi
