#!/usr/bin/env bash

usage() {
  echo "USAGE: run-tests [<test-dir>]"
  echo ""
  echo "Runs any installed toolbox tests"
  echo ""
  echo "  <test-dir>           - The test directory. Expects this file:"
  echo "    test-plan.yaml        - The test plan."
}

set -eo pipefail  # Exit immediately if a command fails.

echo "### Running tests"
tests=$(helm list -n toolbox --no-headers --short)
for test in $tests; do
  echo "#### Running test: $test"
  helm test "$test" -n toolbox --hide-notes --logs
done
