---
apiVersion: v2
name: metrics-snapshot
description: A Helm Chart Toolbox test that snapshots the metrics returned by a PromQL query and compares them against a saved baseline.
type: application
icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
sources:
  - https://github.com/grafana/helm-chart-toolbox/tree/main/charts/metrics-snapshot
version: 0.1.0
appVersion: 0.1.0
maintainers:
  - email: pete.wall@grafana.com
    name: petewall
dependencies: []
