apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart-toolbox.metrics-snapshot.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "query": {{ .Values.query | toJson }},
      "nameLabel": {{ .Values.nameLabel | toJson }},
      "reportThreshold": {{ .Values.reportThreshold }},
      "failThreshold": {{ .Values.failThreshold }},
      "failOnNewMetrics": {{ .Values.failOnNewMetrics }},
      "failOnMissingMetrics": {{ .Values.failOnMissingMetrics }}
    }
