{{- if .Values.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart-toolbox.metrics-snapshot.fullname" . }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
