package helmtestfs

// This file is generated by `make embed-manifests` to populate the manifests/ tree
// from tools/helm-test/manifests. It is intentionally empty here; the directory
// is created and populated during the build step so go:embed picks it up.
