---
name: Build and Release k8s-test

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.os }}/${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32  # v5.0.2
        with:
          go-version: '1.21.x'
          cache: true

      - name: Prepare embedded manifests
        run: make embed-manifests
        working-directory: tools/k8s-test

      - name: Build binary
        working-directory: tools/k8s-test
        shell: bash
        run: |
          mkdir -p dist
          EXT=""
          if [[ "${{ matrix.os }}" == "windows" ]]; then EXT=".exe"; fi
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} CGO_ENABLED=0 \
            go build -ldflags='-s -w' -o "dist/k8s-test_${{ matrix.os }}_${{ matrix.arch }}${EXT}" ./

      - name: Checksums
        working-directory: tools/k8s-test/dist
        run: |
          shasum -a 256 * > SHA256SUMS

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: k8s-test-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            tools/k8s-test/dist/k8s-test_*
            tools/k8s-test/dist/SHA256SUMS

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Flatten artifacts
        run: |
          mkdir -p upload
          find dist -type f -name 'k8s-test_*' -exec cp {} upload/ \;
          # merge checksums
          touch upload/SHA256SUMS
          find dist -type f -name 'SHA256SUMS' -exec cat {} \; >> upload/SHA256SUMS

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: upload/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


