---
name: Test Delay

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
    paths: [charts/delay/**]
  pull_request:
    paths: [charts/delay/**]
  workflow_dispatch:

permissions: {}

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          persist-credentials: 'false'

      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112  # v4.3.0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b  # v2.7.0

      - name: Run tests
        working-directory: charts/delay
        run: make test

  list-integration-tests:
    name: List tests
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.list_tests.outputs.tests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          persist-credentials: 'false'

      - name: List tests
        id: list_tests
        working-directory: charts/delay/tests/integration
        run: |
          tests=$(find . -name test-plan.yaml -exec dirname {} \;)
          echo "Tests: ${tests}"
          echo "tests=$(echo "${tests}" | jq --raw-input --slurp --compact-output 'split("\n") | map(select(. != ""))')" >> "${GITHUB_OUTPUT}"

  run-integration-tests:
    name: Integration Test
    needs: list-integration-tests
    runs-on: ubuntu-latest
    if: needs.list-integration-tests.outputs.tests != '[]'
    strategy:
      matrix:
        test: ${{ fromJson(needs.list-integration-tests.outputs.tests) }}
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          persist-credentials: 'false'
          path: source

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          persist-credentials: 'false'
          repository: grafana/helm-chart-toolbox
          path: helm-chart-toolbox

      - name: Install Flux CLI
        uses: fluxcd/flux2/action@6bf37f6a560fd84982d67f853162e4b3c2235edb  # v2.6.4

      - name: Install Kind CLI
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3  # v1.12.0
        with:
          install_only: true

      - name: Install Minikube CLI
        uses: medyagh/setup-minikube@e3c7f79eb1e997eabccc536a6cf318a2b0fe19d9  # v0.0.20
        with:
          start: false

      - name: Run test
        run: helm-chart-toolbox/tools/helm-test/helm-test "${TEST_DIRECTORY}"
        env:
          TEST_DIRECTORY: "source/charts/delay/tests/integration/${{ matrix.test }}"
          DELETE_CLUSTER: true
