---
name: Test Doc Generator

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
    paths: [tools/doc-generator/**]
  pull_request:
    paths: [tools/doc-generator/**]
  workflow_dispatch:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: 'false'

      - name: Run tests
        working-directory: tools/doc-generator
        run: make test
